function gui_3d(img1, img2, img3, d_num, d_pixel, d_frame)
width = size(img1,2);
height = size(img1,1);
depth = size(img1,3);
x = 10;
y = 10;
z = 2 * d_num;

figure
set(gcf,'Position',[200,200,1000,600]);
ax1 = subplot(width + floor(depth/d_num),height + floor(depth/d_num),[floor(depth/d_num) + 1,(width + floor(depth/d_num)) * height]);
ax2 = subplot(width + floor(depth/d_num),height + floor(depth/d_num),[1,(width + floor(depth/d_num)) * height - width]);
ax3 = subplot(width + floor(depth/d_num),height + floor(depth/d_num),[(width + floor(depth/d_num)) * height + floor(depth/d_num) + 1, (width + floor(depth/d_num)) * height + floor(depth/d_num)]);
imageshow()

% UI object
uicontrol('Style', 'slider',...
    'Min',1,'Max',width,'Value',41,...
    'SliderStep',[1/width 1],...
    'Position', [0 20 200 20],...
    'Callback', @surfxlim); 

uicontrol('Style','text',...
    'Position',[0 45 200 20],...
    'FontSize',12,....
    'Fontweight','bold',.....
    'ForegroundColor','b',...
    'String','x方向');

uicontrol('Style', 'slider',...
    'Min',1,'Max',height,'Value',41,...
    'SliderStep',[1/height 1],...
    'Position', [240 20 200 20],...
    'Callback', @surfylim); 

uicontrol('Style','text',...
    'Position',[240 45 200 20],...
    'FontSize',12,....
    'Fontweight','bold',.....
    'ForegroundColor','g',...
    'String','y方向');

uicontrol('Style', 'slider',...
    'Min',1,'Max',depth,'Value',41,...
    'SliderStep',[1/depth 1],...
    'Position', [480 20 200 20],...
    'Callback', @surfzlim); 
					
uicontrol('Style','text',...
    'Position',[480 45 200 20],...
    'FontSize',12,....
    'Fontweight','bold',.....
    'ForegroundColor','r',...
    'String','z方向');

uicontrol('Style','text',...
    'Position',[0 140 200 20],...
    'String', '座標',.....
    'Fontweight','bold',.....
    'FontSize',12);

t_1 = uicontrol('Style','text',...
    'Position',[0 120 200 20],...
    'String',['x=', num2str(x), ' y=',num2str(y),' z=',num2str(z)],.....
    'Fontweight','bold',.....
    'FontSize',12);
    
uicontrol('Style','text',...
    'Position',[0 90 200 20],...
    'String', '距離（マイクロメートル）',.....
    'Fontweight','bold',.....
    'FontSize',12);

t_2 = uicontrol('Style','text',...
    'Position',[0 70 200 20],...
    'String',['x=', num2str(x * d_pixel), ' ', ' y=',num2str(y * d_pixel),' ',' z=',num2str(z * d_frame),''],.....
    'Fontweight','bold',.....
    'FontSize',12);

function surfxlim(source,~)
    x = round(source.Value);
    imageshow()
end

function surfylim(source,~)
    y = round(source.Value);
    imageshow()
end

function surfzlim(source,~)
    z = round(source.Value);
    imageshow()
end

function imageshow() 
    cla(ax1);
    cla(ax2);
    cla(ax3);
    
    t_1.String = ['x=', num2str(x), ' y=',num2str(y),' z=',num2str(z)];
    t_2.String = ['x=', num2str(x * d_pixel), ' ', ' y=',num2str(y * d_pixel),' ',' z=',num2str(z * d_frame),''];

    ax1 = subplot(12,12,[3,120]);
    imshow(img1(:,:,z),[])
    hold on
    plot(x * ones(1,height + 1), 0:height,'b','LineWidth',1)
    hold on
    plot(0:width, y * ones(1,width + 1),'g','LineWidth',1)
    title('X-Y平面','FontSize',12)
    
    ax2 = subplot(12,12,[1,110]);
    imshow(img3(:,:,x),[])
    hold on
    plot( floor(z/d_num) * ones(1,height + 1), 0:height,'r','LineWidth',1)
    hold on
    plot(0:floor(depth/d_num), y * ones(1, floor(depth/d_num) + 1),'g','LineWidth',1)
    title('Z-Y平面','FontSize',12)
    
    ax3 = subplot(12,12,[123,144]);
    imshow(img2(:,:,y),[])
    hold on
    plot(0:width, floor(z/d_num) * ones(1,width + 1),'r','LineWidth',1)
    hold on
    plot(x * ones(1,floor(depth/d_num) + 1), 0:floor(depth/d_num),'b','LineWidth',1)
    title('X-Z平面','FontSize',12)
    
end

end